### ISSUE TITLE
Google Docs Viewer not working

### ISSUE THREAD

**Issue by SteMotson** [def00111/google-docs-viewer#1]
Re-Installed Google Docs Viewer on Mozilla Firefox browser. When I right click on web search there is no option available for Google Docs Viewer

**Comment by def00111** [comment]
Did you restarted browser?

**Comment by def00111** [comment]
> there is no option available for Google Docs Viewer

What do you mean?

**Comment by def00111** [comment]
What version you have?

**Comment by SteMotson** [comment]
Yes I restarted the browser. 

When I right-click on mouse there should be be an option for Google Docs Viewer - there isn't.

Am using the latest Firefox browser on Windows 10.

**Comment by def00111** [comment]
This is not how the add-on works!

**Comment by SteMotson** [comment]
So how? 

Here's the instructions I have: "After installation, links including a document will display a new option upon right-click entitled, "Open Link in Google DocsViewer".

**Comment by def00111** [comment]
Is this what you want?
https://addons.mozilla.org/firefox/addon/document-viewer/

**Comment by SteMotson** [comment]
No it was definitely Google Docs Viewer. It's part of the OSINT course. I
was given this link
addons.mozilla.org/en-US/firefox/addon/google-docs-viewer-pdf-doc- which I
then added to Firefox. Once added we are instructed to right-click on the
mouse which then produces a list of options. One of the options is "Open
Link in Google Docs Viewer". I am not given this option when I right-click
on the mouse.

Thanks for the other link anyway.



http://www.investigation-services.co.uk
